from tkinter import *

# 계산 식
def salary():
    total_time = int(label_time1.get())+ int(label_time2.get())+ int(label_time3.get())+ int(label_time4.get())+ int(label_time5.get())+ int(label_time6.get())+ int(label_time7.get())+ int(label_time8.get())+ int(label_time9.get())+ int(label_time10.get())+ int(label_time11.get())+ int(label_time12.get())+ int(label_time13.get())+ int(label_time14.get())+ int(label_time15.get())+ int(label_time16.get())+ int(label_time17.get())+ int(label_time18.get())+ int(label_time19.get())+ int(label_time20.get())+ int(label_time21.get())+ int(label_time22.get())+ int(label_time23.get())+ int(label_time24.get())+ int(label_time25.get())+ int(label_time26.get())+ int(label_time27.get())+ int(label_time28.get())+ int(label_time29.get())+ int(label_time30.get())+ int(label_time31.get())+ int(label_time32.get())+ int(label_time33.get())+ int(label_time34.get())+int(label_time35.get())
    total_money = total_time * int(money.get())
    result = Label(result_frame, text=total_money,width=60,textvariable=IntVar)
    result.pack(side="left",fill="y")

# 기본 프레임
root = Tk()
root.title ("Salary_Calculator")
root.geometry("640x500+300+100")

# 설정
setting_frame = LabelFrame(root, text="설정",padx=5, pady=5)
setting_frame.pack(fill="x", ipady=5)

# 시급
label_money = Label(setting_frame, text="시급 :",width=7)
label_money.pack(side="left")

money = Entry(setting_frame, width=10,textvariable= IntVar())
money.pack(side="left")
money.insert(0, "")


# 메인 화면
main_frame = LabelFrame(root, text="메인",padx=5, pady=5)
main_frame.pack(fill="x", ipady=5,side="top")

# 요일 프레임
day_frame = Frame(main_frame)
day_frame.pack(padx=5, pady=10,side="top")

# 리셋 버튼
def btncmd():
    label_time1.delete(0,10)
    label_time2.delete(0,10)
    label_time3.delete(0,10)
    label_time4.delete(0,10)
    label_time5.delete(0,10)
    label_time6.delete(0,10)
    label_time7.delete(0,10)
    label_time8.delete(0,10)
    label_time9.delete(0,10)
    label_time10.delete(0,10)
    label_time11.delete(0,10)
    label_time12.delete(0,10)
    label_time13.delete(0,10)
    label_time14.delete(0,10)
    label_time15.delete(0,10)
    label_time16.delete(0,10)
    label_time17.delete(0,10)
    label_time18.delete(0,10)
    label_time19.delete(0,10)
    label_time20.delete(0,10)
    label_time21.delete(0,10)
    label_time22.delete(0,10)
    label_time23.delete(0,10)
    label_time24.delete(0,10)
    label_time25.delete(0,10)
    label_time26.delete(0,10)
    label_time27.delete(0,10)
    label_time28.delete(0,10)
    label_time29.delete(0,10)
    label_time30.delete(0,10)
    label_time31.delete(0,10)
    label_time32.delete(0,10)
    label_time33.delete(0,10)
    label_time34.delete(0,10)
    label_time35.delete(0,10)
    money.delete(0,100000000)



# 요일
btn_reset = Button(day_frame, text="초기화",width=10,command=btncmd)
btn_reset.pack(side="left")
label1 = Label(day_frame, text="월요일",width=10)
label1.pack(side="left")
label2 = Label(day_frame, text="화요일",width=10)
label2.pack(side="left")
label3 = Label(day_frame, text="수요일",width=10)
label3.pack(side="left")
label4 = Label(day_frame, text="목요일",width=10)
label4.pack(side="left")
label5 = Label(day_frame, text="금요일",width=10)
label5.pack(side="left")
label6 = Label(day_frame, text="토요일",width=10)
label6.pack(side="left")
label7 = Label(day_frame, text="일요일",width=10)
label7.pack(side="left")


# 날짜 기본 프레임
week1_frame = Frame(main_frame)
week1_frame.pack(padx=5,pady=5,side="top")
# 시간 입력 1주차
time_frame = Frame(main_frame)
time_frame.pack(padx=5,side="top")

# 1주차
label_time = Label(week1_frame, text="1주차",width=10)
label_time.pack(side="left")
label_time = Label(time_frame, text="",width=10)
label_time.pack(side="left")
label_time = Label(week1_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time1 = Entry(time_frame, width=10,textvariable=IntVar())
label_time1.pack(side="left")
label_time = Label(week1_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time2 = Entry(time_frame, width=10,textvariable=IntVar())
label_time2.pack(side="left")
label_time = Label(week1_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time3 = Entry(time_frame, width=10,textvariable=IntVar())
label_time3.pack(side="left")
label_time = Label(week1_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time4 = Entry(time_frame, width=10,textvariable=IntVar())
label_time4.pack(side="left")
label_time = Label(week1_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time5 = Entry(time_frame, width=10,textvariable=IntVar())
label_time5.pack(side="left")
label_time = Label(week1_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time6 = Entry(time_frame, width=10,textvariable=IntVar())
label_time6.pack(side="left")
label_time = Label(week1_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time7 = Entry(time_frame, width=10,textvariable=IntVar())
label_time7.pack(side="left")



# 2주차
week2_frame = Frame(main_frame)
week2_frame.pack(padx=5,pady=5,side="top")
# 시간 입력 2주차
time_frame2 = Frame(main_frame)
time_frame2.pack(padx=5,side="top")

label_time = Label(week2_frame, text="2주차",width=10)
label_time.pack(side="left")
label_time = Label(time_frame2, text="",width=10)
label_time.pack(side="left")
label_time = Label(week2_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time8 = Entry(time_frame2, width=10,textvariable=IntVar())
label_time8.pack(side="left")
label_time = Label(week2_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time9 = Entry(time_frame2, width=10,textvariable=IntVar())
label_time9.pack(side="left")
label_time = Label(week2_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time10 = Entry(time_frame2, width=10,textvariable=IntVar())
label_time10.pack(side="left")
label_time = Label(week2_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time11 = Entry(time_frame2, width=10,textvariable=IntVar())
label_time11.pack(side="left")
label_time = Label(week2_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time12 = Entry(time_frame2, width=10,textvariable=IntVar())
label_time12.pack(side="left")
label_time = Label(week2_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time13 = Entry(time_frame2, width=10,textvariable=IntVar())
label_time13.pack(side="left")
label_time = Label(week2_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time14 = Entry(time_frame2, width=10,textvariable=IntVar())
label_time14.pack(side="left")

# 3주차
week3_frame = Frame(main_frame)
week3_frame.pack(padx=5,pady=5,side="top")
# 시간 입력 3주차
time_frame3 = Frame(main_frame)
time_frame3.pack(padx=5,side="top")

label_time = Label(week3_frame, text="3주차",width=10)
label_time.pack(side="left")
label_time = Label(time_frame3, text="",width=10)
label_time.pack(side="left")
label_time = Label(week3_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time15 = Entry(time_frame3, width=10,textvariable=IntVar())
label_time15.pack(side="left")
label_time = Label(week3_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time16 = Entry(time_frame3, width=10,textvariable=IntVar())
label_time16.pack(side="left")
label_time = Label(week3_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time17 = Entry(time_frame3, width=10,textvariable=IntVar())
label_time17.pack(side="left")
label_time = Label(week3_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time18 = Entry(time_frame3, width=10,textvariable=IntVar())
label_time18.pack(side="left")
label_time = Label(week3_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time19 = Entry(time_frame3, width=10,textvariable=IntVar())
label_time19.pack(side="left")
label_time = Label(week3_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time20 = Entry(time_frame3, width=10,textvariable=IntVar())
label_time20.pack(side="left")
label_time = Label(week3_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time21 = Entry(time_frame3, width=10,textvariable=IntVar())
label_time21.pack(side="left")

# 4주차
week4_frame = Frame(main_frame)
week4_frame.pack(padx=5,pady=5,side="top")
# 시간 입력 4주차
time_frame4 = Frame(main_frame)
time_frame4.pack(padx=5,side="top")

label_time = Label(week4_frame, text="4주차",width=10)
label_time.pack(side="left")
label_time = Label(time_frame4, text="",width=10)
label_time.pack(side="left")
label_time = Label(week4_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time22 = Entry(time_frame4, width=10,textvariable=IntVar())
label_time22.pack(side="left")
label_time = Label(week4_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time23 = Entry(time_frame4, width=10,textvariable=IntVar())
label_time23.pack(side="left")
label_time = Label(week4_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time24 = Entry(time_frame4, width=10,textvariable=IntVar())
label_time24.pack(side="left")
label_time = Label(week4_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time25 = Entry(time_frame4, width=10,textvariable=IntVar())
label_time25.pack(side="left")
label_time = Label(week4_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time26 = Entry(time_frame4, width=10,textvariable=IntVar())
label_time26.pack(side="left")
label_time = Label(week4_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time27 = Entry(time_frame4, width=10,textvariable=IntVar())
label_time27.pack(side="left")
label_time = Label(week4_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time28 = Entry(time_frame4, width=10,textvariable=IntVar())
label_time28.pack(side="left")

# 5주차
week5_frame = Frame(main_frame)
week5_frame.pack(padx=5,pady=5,side="top")
# 시간 입력 5주차
time_frame5 = Frame(main_frame)
time_frame5.pack(padx=5,side="top")

label_time = Label(week5_frame, text="5주차",width=10)
label_time.pack(side="left")
label_time = Label(time_frame5, text="",width=10)
label_time.pack(side="left")
label_time = Label(week5_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time29 = Entry(time_frame5, width=10,textvariable=IntVar())
label_time29.pack(side="left")
label_time = Label(week5_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time30 = Entry(time_frame5, width=10,textvariable=IntVar())
label_time30.pack(side="left")
label_time = Label(week5_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time31 = Entry(time_frame5, width=10,textvariable=IntVar())
label_time31.pack(side="left")
label_time = Label(week5_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time32 = Entry(time_frame5, width=10,textvariable=IntVar())
label_time32.pack(side="left")
label_time = Label(week5_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time33 = Entry(time_frame5, width=10,textvariable=IntVar())
label_time33.pack(side="left")
label_time = Label(week5_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time34 = Entry(time_frame5, width=10,textvariable=IntVar())
label_time34.pack(side="left")
label_time = Label(week5_frame, text="일한 시간",width=10)
label_time.pack(side="left")
label_time35 = Entry(time_frame5, width=10,textvariable=IntVar())
label_time35.pack(side="left")

# 결과
result_frame = LabelFrame(root, text="결과 값 보기",padx=5, pady=5)
result_frame.pack(fill="x", ipady=5,side="top")

# 월급
label_result = Label(result_frame, text="월급 :",width=15)
label_result.pack(side="left",fill="y")


# 시작 버튼 동작
def btncmd():
    salary()
btn_start = Button(result_frame, text="결과 보기", command=btncmd,height=2)
btn_start.pack(side="right")

root.mainloop()